// Weapons.js — fictional arcade weapon definitions. No real firearm brands
// or models are referenced; these are original, stylized arcade tools.

export const WEAPONS = {
  blaster: {
    key: 'blaster',
    name: '5600 COMPACT BLASTER',
    kind: 'blaster',
    damage: 15,
    pellets: 1,
    fireInterval: 0.12,
    magSize: 24,
    reserveMax: 144,
    reloadTime: 1.0,
    spread: 0.018,
    auto: true,
    range: 60,
    recoil: 0.018,
  },
  pump: {
    key: 'pump',
    name: 'BROAD STREET PUMP',
    kind: 'pump',
    damage: 0,
    pellets: 7,
    pelletDamage: 11,
    fireInterval: 0.85,
    magSize: 6,
    reserveMax: 36,
    reloadTime: 1.9,
    spread: 0.09,
    auto: false,
    range: 24,
    recoil: 0.09,
  },
  rapid: {
    key: 'rapid',
    name: 'OVERBROOK RAPID',
    kind: 'rapid',
    damage: 7,
    pellets: 1,
    fireInterval: 0.065,
    magSize: 42,
    reserveMax: 210,
    reloadTime: 1.6,
    spread: 0.05,
    auto: true,
    range: 55,
    recoil: 0.012,
  },
  flash: {
    key: 'flash',
    name: 'PHILLY FLASH',
    kind: 'flash',
    damage: 4,
    pellets: 1,
    fireInterval: 1.3,
    magSize: 1,
    reserveMax: 4,
    reloadTime: 1.5,
    spread: 0,
    auto: false,
    range: 14,
    recoil: 0.05,
    stun: true,
    stunRadius: 9,
    stunDuration: 4.5,
  },
};

export const WEAPON_ORDER = ['blaster', 'pump', 'rapid', 'flash'];
